kind: pipeline
name: default

steps:
- name: Test and Build
  image: maven:3.6-jdk-8-alpine
  commands:
  - mvn test
  - mvn -DskipTests -Dmaven.test.failure.ignore-true clean package
  when:
    branch: [development]
- name: Deploy
  image: maven:3.6-jdk-8-alpine
  environment:
    anypoint_userName:
      from_secret: username
    anypoint_passwrd:
      from_secret: password
  commands:
  - mvn -Dmaven.test.failure.ignore-true clean deploy -DmuleDeploy -DskipTests -Dmule.version=4.4.0 -Dusername=$${anypoint_userName} -Dpassword=$${anypoint_passwrd} -Denvironment=Sandbox -Dcloudhub.application.name=democicdanshu
  when:
    branch: [development]    
