name: Bump version
on:
  pull_request:
    branches: [main]
    types: [closed]
    
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: hennejg/github-tag-action@v4.3.1
      id: semver
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
