# This is a basic workflow to help you get started with Actions

name: Rollback to previous version

# Controls when the workflow will run
on:
  
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'version of the artifact'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download Maven Artifact
        id: download-maven-artifact
        uses: clausnz/github-action-download-maven-artifact@master
        with:
          url: 'https://916d-2600-8804-289-800-113c-299b-e8f1-37b7.ngrok.io/repository'
          repository: 'maven-releases'
          groupId: 'com.tm'
          artifactId: 'MuleDemo'
          version: ${{github.event.inputs.versionNumber}}
          extension: 'jar'
          username: admin
          password: ${{ secrets.MVN_PWD }}

      - name: Output file path in container
        run: |
          echo "File has been downloaded to ${{ steps.download-maven-artifact.outputs.file }}"
      - uses: actions/checkout@v3    
      - name: Deploy to Sandbox
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          artifactName=$(basename ${{ steps.download-maven-artifact.outputs.file }})
          mvn deploy -DmuleDeploy \
           -Dmule.artifact=$artifactName \
           -Dmule.version=4.4.0 \
           -Dusername="$USERNAME" \
           -Dpassword="$PASSWORD" \
           -Denvironment=Sandbox \
           -Dcloudhub.application.name=democicdanshu22 \
           -DskipTests    
